// AlicetleLabs Business OS — shared Orders / Payments layer for Admin.
let business = { orders: [], payments: [], bookings: [], jobs: [], requests: [], goal: 10000 };
let editingJobId = null;
let bookingDateIds = [];
const money = value => `฿${Number(value || 0).toLocaleString('th-TH', { maximumFractionDigits: 2 })}`;
const todayISO = () => new Date().toISOString().slice(0, 10);
const shortDate = value => value ? new Date(`${value.slice(0, 10)}T00:00:00`).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' }).toUpperCase() : '—';
const longDate = value => value ? new Date(value).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }) : '—';
const businessOrder = id => business.orders.find(order => order.id === id);
const businessPaid = orderId => business.payments.filter(payment => payment.order_id === orderId).reduce((sum, payment) => sum + Number(payment.amount || 0), 0);
const orderBalance = order => Math.max(0, Number(order.total || 0) - businessPaid(order.id));
const paymentState = order => { const paid = businessPaid(order.id), total = Number(order.total || 0); return paid <= 0 ? 'UNPAID' : paid < total ? 'PARTIAL' : 'PAID'; };
const paymentClass = state => state === 'PAID' ? 'good' : state === 'PARTIAL' ? 'warn' : 'bad';
const sourceLabel = source => source === 'rental' ? 'Rental' : 'Job';
const jobStatusLabel = status => ({ new: 'NEW', in_progress: 'IN PROGRESS', delivered: 'DELIVERED', cancelled: 'CANCELLED' }[status] || status);
const bookingStatusLabel = status => ({ confirmed: 'CONFIRMED', active: 'ACTIVE', completed: 'COMPLETED', cancelled: 'CANCELLED' }[status] || status);

function activeOrders() { return business.orders.filter(order => order.status !== 'cancelled'); }
function activeBookings() { return business.bookings.filter(booking => booking.booking_status !== 'cancelled'); }
function activeJobs() { return business.jobs.filter(job => job.job_status !== 'cancelled'); }
function financialSummary() {
  const orders = activeOrders();
  const sales = orders.reduce((sum, order) => sum + Number(order.total || 0), 0);
  const collected = orders.reduce((sum, order) => sum + businessPaid(order.id), 0);
  return { orders, sales, collected, outstanding: orders.reduce((sum, order) => sum + orderBalance(order), 0) };
}
function showBusinessError(error) { const message = supabaseError(error); if (typeof setSaveStatus === 'function') setSaveStatus(message, 'error'); return message; }

async function loadBusinessData() {
  if (!SUPABASE_READY || !supabaseClient) return;
  try {
    const client = requireSupabase();
    const [orders, payments, bookings, jobs, requests, settings] = await Promise.all([
      client.from('orders').select('*').order('created_at', { ascending: false }),
      client.from('payments').select('*').order('paid_at', { ascending: false }),
      client.from('rental_bookings').select('*,events(name,venue)').order('start_date', { ascending: true }),
      client.from('jobs').select('*').order('created_at', { ascending: false }),
      client.from('booking_requests').select('*,events(name,venue,pickup)').order('created_at', { ascending: false }),
      client.from('business_settings').select('value').eq('key', 'monthly_goal').maybeSingle()
    ]);
    for (const result of [orders, payments, bookings, jobs, settings]) if (result.error) throw result.error;
    // Keep the existing admin usable while the one-time booking-requests migration
    // is being applied. Once the table exists, requests load normally.
    if (requests.error) {
      const missingRequestsTable = ['42P01', 'PGRST205'].includes(requests.error.code) || /booking_requests/i.test(requests.error.message || '');
      if (!missingRequestsTable) throw requests.error;
      console.warn('[Business OS] booking_requests table is not ready yet');
    }
    business.orders = orders.data || [];
    business.payments = payments.data || [];
    business.bookings = bookings.data || [];
    business.jobs = jobs.data || [];
    business.requests = requests.data || [];
    business.goal = Number(settings.data?.value?.amount || 10000);
    renderBusiness();
  } catch (error) {
    console.error('[Business OS]', error);
    const message = supabaseError(error);
    ['requestList', 'bookingList', 'jobGrid', 'financeList'].forEach(id => { const node = document.getElementById(id); if (node) node.innerHTML = `<div class="emptySoft">โหลด Business OS ไม่สำเร็จ<br>${message}</div>`; });
  }
}

function renderBusiness() {
  renderDashboard(); renderJobs(); renderPOS(); renderBookings(); renderRequests();
}

function renderDashboard() {
  const summary = financialSummary(), orders = summary.orders;
  const rentalSales = orders.filter(order => order.source_type === 'rental').reduce((sum, order) => sum + Number(order.total || 0), 0);
  const jobSales = orders.filter(order => order.source_type === 'job').reduce((sum, order) => sum + Number(order.total || 0), 0);
  const percent = summary.sales ? Math.min(100, summary.collected / summary.sales * 100) : 0;
  const now = new Date(), hour = now.getHours();
  const greeting = hour < 12 ? 'สวัสดีตอนเช้า' : hour < 18 ? 'สวัสดีตอนบ่าย' : 'สวัสดีตอนเย็น';
  const setText = (id, text) => { const node = document.getElementById(id); if (node) node.textContent = text; };
  setText('dashGreeting', `${greeting} พี่อลิส ♡`); setText('dashDate', now.toLocaleDateString('th-TH', { day: 'numeric', month: 'long', year: 'numeric' }));
  setText('kpiSales', money(summary.sales)); setText('kpiSalesMeta', `${orders.length} orders`); setText('kpiCollected', money(summary.collected)); setText('kpiCollectedMeta', `${percent.toFixed(1)}% ของยอดขาย`); setText('kpiOutstanding', money(summary.outstanding)); setText('kpiOutstandingMeta', `${orders.filter(order => orderBalance(order) > 0).length} รายการรอรับ`); setText('kpiOrders', String(orders.length)); setText('kpiOrdersMeta', `Rental ${orders.filter(order => order.source_type === 'rental').length} · Jobs ${orders.filter(order => order.source_type === 'job').length}`);
  const progress = document.getElementById('collectedProgress'); if (progress) progress.style.width = `${percent}%`;
  const sourceTotal = rentalSales + jobSales || 1;
  const sourceList = document.getElementById('sourceList'); if (sourceList) sourceList.innerHTML = [['Rental', rentalSales], ['Jobs', jobSales]].map(([label, value]) => `<div class="sourceLine"><span>${label}</span><div class="bar"><i style="width:${Math.round(value / sourceTotal * 100)}%"></i></div><b>${money(value)}</b></div>`).join('');
  const monthSales = orders.filter(order => { const date = new Date(order.created_at); return date.getFullYear() === now.getFullYear() && date.getMonth() === now.getMonth(); }).reduce((sum, order) => sum + Number(order.total || 0), 0);
  setText('goalValue', `${money(monthSales)} / ${money(business.goal)}`); const goalProgress = document.getElementById('goalProgress'); if (goalProgress) goalProgress.style.width = `${Math.min(100, business.goal ? monthSales / business.goal * 100 : 0)}%`;
  renderTrend(30); renderUpcoming(); renderActiveJobs(); renderRecentPayments();
}

function renderTrend(days = 30) {
  const svg = document.getElementById('trendSvg'); if (!svg) return;
  const end = new Date(); end.setHours(23, 59, 59, 999); const start = new Date(end); start.setDate(start.getDate() - days + 1); const points = Array.from({ length: Math.min(days, 60) }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + Math.round(index * (days - 1) / (Math.min(days, 60) - 1 || 1))); return date; });
  const sales = points.map(date => business.orders.filter(order => order.status !== 'cancelled' && new Date(order.created_at).toDateString() === date.toDateString()).reduce((sum, order) => sum + Number(order.total || 0), 0));
  const paid = points.map(date => business.payments.filter(payment => new Date(payment.paid_at).toDateString() === date.toDateString()).reduce((sum, payment) => sum + Number(payment.amount || 0), 0));
  const max = Math.max(1, ...sales, ...paid), x = index => 18 + index * (564 / Math.max(1, points.length - 1)), y = value => 132 - (value / max * 106);
  const path = values => values.map((value, index) => `${index ? 'L' : 'M'} ${x(index).toFixed(1)} ${y(value).toFixed(1)}`).join(' ');
  svg.innerHTML = `<path d="M18 132 H582" stroke="#eee8f2"/><path d="${path(sales)}" fill="none" stroke="#9270df" stroke-width="3" stroke-linecap="round"/><path d="${path(paid)}" fill="none" stroke="#67b483" stroke-width="3" stroke-linecap="round"/><circle cx="${x(sales.length - 1)}" cy="${y(sales.at(-1) || 0)}" r="4" fill="#9270df"/><circle cx="${x(paid.length - 1)}" cy="${y(paid.at(-1) || 0)}" r="4" fill="#67b483"/>`;
}
function renderUpcoming() { const node = document.getElementById('upcomingList'); if (!node) return; const rows = activeBookings().filter(booking => booking.start_date >= todayISO()).slice(0, 4); node.innerHTML = rows.length ? rows.map(booking => `<div class="miniItem"><div><b>${booking.events?.name || 'Rental'}</b><span>${shortDate(booking.start_date)} · ${booking.customer_name}</span></div><span class="statusPill">${bookingStatusLabel(booking.booking_status)}</span></div>`).join('') : '<div class="emptySoft">ยังไม่มี booking ใกล้ ๆ ♡</div>'; }
function renderActiveJobs() { const node = document.getElementById('activeJobsList'); if (!node) return; const rows = activeJobs().filter(job => job.job_status !== 'delivered').slice(0, 4); node.innerHTML = rows.length ? rows.map(job => `<div class="miniItem"><div><b>${escapeHtml(job.job_name)}</b><span>${escapeHtml(job.customer_name)} · ${job.due_date ? `ส่ง ${shortDate(job.due_date)}` : 'ยังไม่กำหนดส่ง'}</span></div><span class="statusPill warn">${jobStatusLabel(job.job_status)}</span></div>`).join('') : '<div class="emptySoft">All caught up ♡</div>'; }
function renderRecentPayments() { const node = document.getElementById('recentPaymentsList'); if (!node) return; const rows = business.payments.slice(0, 4); node.innerHTML = rows.length ? rows.map(payment => { const order = businessOrder(payment.order_id); return `<div class="miniItem"><div><b>${money(payment.amount)}</b><span>${sourceLabel(order?.source_type)} · ${longDate(payment.paid_at)}</span></div><span class="statusPill good">รับแล้ว</span></div>`; }).join('') : '<div class="emptySoft">ยังไม่มีเงินเข้า</div>'; }
function renderBookings() { const node = document.getElementById('bookingList'); if (!node) return; const rows = business.bookings.slice(0, 8); node.innerHTML = rows.length ? rows.map(booking => { const order = businessOrder(booking.order_id), state = order ? paymentState(order) : 'UNPAID'; return `<div class="financeRow"><button class="bookingSummary" onclick="openBookingDetail('${booking.id}')"><b>${escapeHtml(booking.events?.name || 'Rental')}</b><small>${shortDate(booking.start_date)} — ${shortDate(booking.end_date)} · ${escapeHtml(booking.customer_name)}</small></button><span class="statusPill ${paymentClass(state)}">${state}</span><button class="tinyBtn" onclick="openPaymentModal('${booking.order_id || ''}')">รับเงิน</button></div>`; }).join('') : '<div class="emptySoft">ยังไม่มี booking ที่บันทึกไว้ ♡</div>'; }
function renderRequests() { const node = document.getElementById('requestList'); if (!node) return; const rows = business.requests.filter(request => request.request_status === 'pending'); node.innerHTML = rows.length ? rows.map(request => `<div class="requestCard"><div><b>${escapeHtml(request.events?.name || 'Rental')}</b><small>${(request.selected_dates || []).map(shortDate).join(' · ')} · ${money(request.rental_total)}</small><p>${escapeHtml(request.message || 'คำขอจากลูกค้าใน LINE')}</p></div><button class="tinyBtn primaryTiny" onclick="confirmBookingRequest('${request.id}')">ยืนยันและสร้าง Order</button></div>`).join('') : '<div class="emptySoft">ยังไม่มีคำขอจองจากลูกค้า ♡</div>'; }
function renderJobs() { const node = document.getElementById('jobGrid'); if (!node) return; node.innerHTML = business.jobs.length ? business.jobs.map(job => { const order = businessOrder(job.order_id), state = order ? paymentState(order) : 'UNPAID'; return `<article class="jobCard"><div class="jobTop"><div><h3>${escapeHtml(job.job_name)}</h3><div class="jobMeta">${escapeHtml(job.customer_name)} · ${escapeHtml(job.category || 'Other')}</div></div><span class="statusPill ${paymentClass(state)}">${state}</span></div><div class="jobPrice">${money(job.price)}</div><div class="jobFoot"><button class="jobStatus ${job.job_status}" onclick="cycleJobStatus('${job.id}')">${jobStatusLabel(job.job_status)}</button><span class="jobMeta">${job.due_date ? `ส่ง ${shortDate(job.due_date)}` : `รับ ${shortDate(job.received_date)}`}</span></div><div class="jobActions"><button class="tinyBtn" onclick="openJobModal('${job.id}')">แก้ไข</button><button class="tinyBtn" onclick="openPaymentModal('${job.order_id || ''}')">รับเงิน</button></div></article>`; }).join('') : '<div class="emptySoft">nothing here yet ♡<br>งานถัดไปของพี่จะมาอยู่ตรงนี้</div>'; }
function renderPOS(tab = document.querySelector('.posTabs button.on')?.dataset.postab || 'orders') { const summary = financialSummary(); const setText = (id, value) => { const node = document.getElementById(id); if (node) node.textContent = money(value); }; setText('posSales', summary.sales); setText('posCollected', summary.collected); setText('posOutstanding', summary.outstanding); const node = document.getElementById('financeList'); if (!node) return; document.querySelectorAll('[data-postab]').forEach(button => button.classList.toggle('on', button.dataset.postab === tab)); let rows = []; if (tab === 'payments') rows = business.payments.map(payment => ({ title: money(payment.amount), meta: `${longDate(payment.paid_at)} · ${payment.method}`, amount: Number(payment.amount), state: 'รับแล้ว', orderId: payment.order_id })); else if (tab === 'outstanding') rows = activeOrders().filter(order => orderBalance(order) > 0).map(order => ({ title: `${sourceLabel(order.source_type)} order`, meta: `${longDate(order.created_at)} · ${paymentState(order)}`, amount: orderBalance(order), state: 'รอรับ', orderId: order.id })); else rows = activeOrders().map(order => ({ title: `${sourceLabel(order.source_type)} order`, meta: `${longDate(order.created_at)} · ${paymentState(order)}`, amount: Number(order.total), state: paymentState(order), orderId: order.id })); node.innerHTML = rows.length ? rows.map(row => `<div class="financeRow"><div><b>${escapeHtml(row.title)}</b><small>${escapeHtml(row.meta)}</small></div><strong class="financeAmount">${money(row.amount)}</strong><span class="statusPill ${paymentClass(row.state === 'รับแล้ว' ? 'PAID' : row.state)}">${row.state}</span>${tab !== 'payments' ? `<button class="tinyBtn" onclick="openPaymentModal('${row.orderId}')">＋เงิน</button>` : ''}</div>`).join('') : '<div class="emptySoft">nothing here yet ♡</div>'; }

function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character])); }
function closeBusinessModal(id) { document.getElementById(id)?.classList.remove('on'); }
function openBookingModal(eventId = '', dateId = '') { const select = document.getElementById('bookingEvent'); if (!select) return; select.innerHTML = (data || []).map(event => `<option value="${event.id}">${escapeHtml(event.name)}</option>`).join(''); if (eventId) select.value = eventId; bookingDateIds = dateId ? [dateId] : []; document.getElementById('bookingCustomer').value = ''; document.getElementById('bookingLine').value = ''; document.getElementById('bookingNotes').value = ''; document.getElementById('bookingReceived').value = '0'; document.getElementById('bookingTotal').value = ''; document.getElementById('bookingPickup').value = ''; document.getElementById('bookingReturn').value = ''; renderBookingDates(); document.getElementById('bookingModal').classList.add('on'); }
function renderBookingDates() { const event = data.find(item => item.id === document.getElementById('bookingEvent')?.value), node = document.getElementById('bookingDates'); if (!event || !node) return; node.innerHTML = event.dates.filter(date => date.status === 'available' || bookingDateIds.includes(date.id)).map(date => `<label><input type="checkbox" value="${date.id}" ${bookingDateIds.includes(date.id) ? 'checked' : ''} onchange="updateBookingQuote()">${displayDate(date.event_date)}</label>`).join('') || '<span class="jobMeta">ไม่มีวันที่ว่าง</span>'; updateBookingQuote(); }
function updateBookingQuote() { const event = data.find(item => item.id === document.getElementById('bookingEvent')?.value), checked = [...document.querySelectorAll('#bookingDates input:checked')].map(input => input.value); bookingDateIds = checked; if (!event || !checked.length) return; const selected = event.dates.filter(date => checked.includes(date.id)).sort((a, b) => a.event_date.localeCompare(b.event_date)), daily = event.early_bird_active && event.early_bird_price != null ? Math.min(Number(event.base_price), Number(event.early_bird_price)) : Number(event.base_price), discounts = Object.fromEntries(event.promotions.map(promo => [promo.days, Number(promo.discount_amount)])), discount = Number(discounts[selected.length] || 0), total = Math.max(0, daily * selected.length - discount); document.getElementById('bookingTotal').value = total; document.getElementById('bookingPickup').value ||= event.pickup; document.getElementById('bookingReturn').value ||= event.pickup; }
function selectedBookingDates() { const event = data.find(item => item.id === document.getElementById('bookingEvent')?.value); return event ? event.dates.filter(date => bookingDateIds.includes(date.id)).sort((a, b) => a.event_date.localeCompare(b.event_date)) : []; }

async function createRentalBooking() { const selected = selectedBookingDates(), eventId = document.getElementById('bookingEvent').value, customer = document.getElementById('bookingCustomer').value.trim(), total = Number(document.getElementById('bookingTotal').value || 0), received = Number(document.getElementById('bookingReceived').value || 0); if (!selected.length || !customer || total < 0) return alert('กรุณาเลือกวันที่ ชื่อลูกค้า และยอดเช่า'); if (received < 0 || received > total) return alert('ยอดรับเงินต้องไม่เกินยอดเช่ารวม'); const client = requireSupabase(), bookingId = crypto.randomUUID(), orderId = crypto.randomUUID(); try { const { error: orderError } = await client.from('orders').insert({ id: orderId, source_type: 'rental', source_id: bookingId, total, status: 'open' }); if (orderError) throw orderError; const { error: bookingError } = await client.from('rental_bookings').insert({ id: bookingId, order_id: orderId, event_id: eventId, date_ids: selected.map(date => date.id), customer_name: customer, line_contact: document.getElementById('bookingLine').value.trim(), start_date: selected[0].event_date, end_date: selected.at(-1).event_date, pickup_location: document.getElementById('bookingPickup').value.trim(), return_location: document.getElementById('bookingReturn').value.trim(), rental_total: total, notes: document.getElementById('bookingNotes').value.trim() }); if (bookingError) throw bookingError; if (received > 0) { const { error: paymentError } = await client.from('payments').insert({ order_id: orderId, amount: received, method: document.getElementById('bookingMethod').value, note: 'Initial payment' }); if (paymentError) throw paymentError; } const { data: updatedDates, error: dateError } = await client.from('event_dates').update({ status: 'booked' }).in('id', selected.map(date => date.id)).eq('status', 'available').select('id'); if (dateError) throw dateError; if ((updatedDates || []).length !== selected.length) throw new Error('บางวันที่ถูกเปลี่ยนสถานะไปแล้ว กรุณาตรวจสอบคิว'); closeBusinessModal('bookingModal'); showResultModal('บันทึก Booking สำเร็จ', `${customer} · ${money(total)}\nออเดอร์และข้อมูลการรับเงินถูกบันทึกแล้ว`, 'success'); await Promise.all([loadAdminData(), loadBusinessData()]); } catch (error) { await client.from('payments').delete().eq('order_id', orderId); await client.from('rental_bookings').delete().eq('id', bookingId); await client.from('orders').delete().eq('id', orderId); showResultModal('สร้าง Booking ไม่สำเร็จ', supabaseError(error), 'error'); } }

async function confirmBookingRequest(id) { const request = business.requests.find(item => item.id === id); if (!request) return; const client = requireSupabase(), bookingId = crypto.randomUUID(), orderId = crypto.randomUUID(), dates = request.date_ids || []; try { const { error: orderError } = await client.from('orders').insert({ id: orderId, source_type: 'rental', source_id: bookingId, total: request.rental_total, status: 'open' }); if (orderError) throw orderError; const { error: bookingError } = await client.from('rental_bookings').insert({ id: bookingId, order_id: orderId, event_id: request.event_id, date_ids: dates, customer_name: 'ลูกค้าจาก LINE', line_contact: '', start_date: request.start_date, end_date: request.end_date, pickup_location: request.pickup_location || request.events?.pickup || '', return_location: request.return_location || request.events?.pickup || '', rental_total: request.rental_total, notes: request.message || '' }); if (bookingError) throw bookingError; const { data: updatedDates, error: dateError } = await client.from('event_dates').update({ status: 'booked' }).in('id', dates).eq('status', 'available').select('id'); if (dateError) throw dateError; if ((updatedDates || []).length !== dates.length) throw new Error('บางวันที่ถูกเลือกถูกจองไปแล้ว'); const { error: requestError } = await client.from('booking_requests').update({ request_status: 'confirmed' }).eq('id', id); if (requestError) throw requestError; showResultModal('สร้าง Order สำเร็จ ♡', 'คำขอจากลูกค้าถูกเปลี่ยนเป็น Booking และ Order แล้ว', 'success'); await Promise.all([loadAdminData(), loadBusinessData()]); } catch (error) { await client.from('event_dates').update({ status: 'available' }).in('id', dates).eq('status', 'booked'); await client.from('rental_bookings').delete().eq('id', bookingId); await client.from('orders').delete().eq('id', orderId); showResultModal('ยืนยันคำขอไม่สำเร็จ', supabaseError(error), 'error'); } }

function openJobModal(id = '') { editingJobId = id || null; const job = id ? business.jobs.find(item => item.id === id) : null; document.getElementById('jobModalTitle').textContent = job ? 'แก้ไข Job ♡' : 'New Job ♡'; document.getElementById('jobCustomer').value = job?.customer_name || ''; document.getElementById('jobName').value = job?.job_name || ''; document.getElementById('jobCategory').value = job?.category || 'other'; document.getElementById('jobStatus').value = job?.job_status || 'new'; document.getElementById('jobReceived').value = job?.received_date || todayISO(); document.getElementById('jobDue').value = job?.due_date || ''; document.getElementById('jobPrice').value = job?.price ?? ''; document.getElementById('jobNotes').value = job?.notes || ''; document.getElementById('jobModal').classList.add('on'); }
async function saveJob() { const customer = document.getElementById('jobCustomer').value.trim(), name = document.getElementById('jobName').value.trim(), price = Number(document.getElementById('jobPrice').value || 0); if (!customer || !name || price < 0) return alert('กรุณากรอกลูกค้า ชื่องาน และราคา'); const client = requireSupabase(), payload = { customer_name: customer, job_name: name, category: document.getElementById('jobCategory').value, received_date: document.getElementById('jobReceived').value || todayISO(), due_date: document.getElementById('jobDue').value || null, price, job_status: document.getElementById('jobStatus').value, notes: document.getElementById('jobNotes').value.trim() }; try { if (editingJobId) { const job = business.jobs.find(item => item.id === editingJobId); const { error } = await client.from('jobs').update(payload).eq('id', editingJobId); if (error) throw error; if (job?.order_id) { const { error: orderError } = await client.from('orders').update({ total: price }).eq('id', job.order_id); if (orderError) throw orderError; } } else { const jobId = crypto.randomUUID(), orderId = crypto.randomUUID(); const { error: orderError } = await client.from('orders').insert({ id: orderId, source_type: 'job', source_id: jobId, total: price, status: 'open' }); if (orderError) throw orderError; const { error } = await client.from('jobs').insert({ id: jobId, order_id: orderId, ...payload }); if (error) { await client.from('orders').delete().eq('id', orderId); throw error; } } closeBusinessModal('jobModal'); await loadBusinessData(); showResultModal('บันทึก Job สำเร็จ', `${name}\n${money(price)} ถูกเพิ่มใน Orders แล้ว`, 'success'); } catch (error) { showResultModal('บันทึก Job ไม่สำเร็จ', supabaseError(error), 'error'); } }
async function cycleJobStatus(id) { const job = business.jobs.find(item => item.id === id); if (!job) return; const order = businessOrder(job.order_id); const orderStatus = document.querySelector('.jobStatus')?.value; const next = { new: 'in_progress', in_progress: 'delivered', delivered: 'cancelled', cancelled: 'new' }[job.job_status] || 'new'; if (next === 'cancelled' && !confirm('ยกเลิกงานนี้หรือไม่? ประวัติ Order และ Payment จะยังอยู่')) return; const { error } = await requireSupabase().from('jobs').update({ job_status: next }).eq('id', id); if (error) return alert(supabaseError(error)); if (order && next === 'cancelled') await requireSupabase().from('orders').update({ status: 'cancelled' }).eq('id', order.id); await loadBusinessData(); }

function openPaymentModal(orderId = '') { const select = document.getElementById('paymentOrder'), submit = document.querySelector('#paymentModal .submit'); const rows = activeOrders(); select.innerHTML = rows.map(order => `<option value="${order.id}">${sourceLabel(order.source_type)} · ${money(order.total)} · ค้าง ${money(orderBalance(order))}</option>`).join(''); if (!rows.length) { select.innerHTML = '<option value="">ยังไม่มี Order ที่ยืนยันแล้ว</option>'; } if (orderId) select.value = orderId; document.getElementById('paymentAmount').value = orderId && businessOrder(orderId) ? orderBalance(businessOrder(orderId)) || '' : ''; document.getElementById('paymentDate').value = new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16); document.getElementById('paymentNote').value = ''; if (submit) submit.disabled = !rows.length; document.getElementById('paymentModal').classList.add('on'); }
function openBookingDetail(id) { const booking = business.bookings.find(item => item.id === id); if (!booking) return; const order = businessOrder(booking.order_id), state = order ? paymentState(order) : 'UNPAID', dates = (booking.date_ids || []).length ? `${shortDate(booking.start_date)} — ${shortDate(booking.end_date)}` : '—'; document.getElementById('bookingDetailContent').innerHTML = `<div class="detailLine"><span>งาน</span><b>${escapeHtml(booking.events?.name || 'Rental')}</b></div><div class="detailLine"><span>ลูกค้า</span><b>${escapeHtml(booking.customer_name)}</b></div><div class="detailLine"><span>วันเช่า</span><b>${dates}</b></div><div class="detailLine"><span>รับ–คืน</span><b>${escapeHtml(booking.pickup_location || '—')} → ${escapeHtml(booking.return_location || '—')}</b></div><div class="detailLine"><span>ยอดรวม</span><b>${money(booking.rental_total)}</b></div><div class="detailLine"><span>สถานะเงิน</span><b class="statusPill ${paymentClass(state)}">${state} · ค้าง ${money(order ? orderBalance(order) : booking.rental_total)}</b></div>${booking.line_contact ? `<div class="detailLine"><span>LINE</span><b>${escapeHtml(booking.line_contact)}</b></div>` : ''}${booking.notes ? `<div class="detailLine"><span>หมายเหตุ</span><b>${escapeHtml(booking.notes)}</b></div>` : ''}`; const paymentButton = document.getElementById('bookingDetailPayment'); paymentButton.onclick = () => { closeBusinessModal('bookingDetailModal'); openPaymentModal(booking.order_id || ''); }; document.getElementById('bookingDetailModal').classList.add('on'); }
async function recordPayment() { const orderId = document.getElementById('paymentOrder').value, order = businessOrder(orderId), amount = Number(document.getElementById('paymentAmount').value || 0); if (!order || amount <= 0) return alert('ยังไม่มี Order ที่ยืนยันแล้ว กรุณายืนยันคำขอจองจากฝั่งลูกค้าก่อน'); if (amount > orderBalance(order)) return alert(`รับเงินได้สูงสุด ${money(orderBalance(order))} สำหรับ Order นี้`); const { error } = await requireSupabase().from('payments').insert({ order_id: orderId, amount, paid_at: new Date(document.getElementById('paymentDate').value).toISOString(), method: document.getElementById('paymentMethod').value, note: document.getElementById('paymentNote').value.trim() }); if (error) return showResultModal('บันทึกเงินไม่สำเร็จ', supabaseError(error), 'error'); closeBusinessModal('paymentModal'); await loadBusinessData(); showResultModal('รับเงินสำเร็จ ♡', `${money(amount)} เพิ่มใน Payment history แล้ว`, 'success'); }

async function editGoal() { const current = business.goal || 10000, value = prompt('ตั้งเป้ารายได้เดือนนี้ (บาท)', String(current)); if (value === null || Number(value) < 0) return; const { error } = await requireSupabase().from('business_settings').upsert({ key: 'monthly_goal', value: { amount: Number(value) } }); if (error) return alert(supabaseError(error)); business.goal = Number(value); renderDashboard(); }
async function cancelBookingFromDate(dateId) { const booking = business.bookings.find(item => (item.date_ids || []).includes(dateId) && item.booking_status !== 'cancelled'); if (!booking) return false; if (!confirm('ยกเลิก Booking นี้และคืนวันที่กลับเป็นว่างหรือไม่? ประวัติการเงินจะยังอยู่')) return true; const client = requireSupabase(); await client.from('rental_bookings').update({ booking_status: 'cancelled' }).eq('id', booking.id); if (booking.order_id) await client.from('orders').update({ status: 'cancelled' }).eq('id', booking.order_id); await client.from('event_dates').update({ status: 'available' }).in('id', booking.date_ids || []); await Promise.all([loadAdminData(), loadBusinessData()]); return true; }
window.cycle = async function(eventId, dateId) { const event = data.find(item => item.id === eventId), date = event?.dates.find(item => item.id === dateId); if (!date) return; if (date.status === 'available') return openBookingModal(eventId, dateId); if (date.status === 'pending') { const { error } = await requireSupabase().from('event_dates').update({ status: 'available' }).eq('id', dateId); if (error) return alert(supabaseError(error)); return loadAdminData(); } await cancelBookingFromDate(dateId); };

document.querySelectorAll('.adminNav button').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('.adminNav button').forEach(item => item.classList.remove('on')); button.classList.add('on'); document.querySelectorAll('.adminView').forEach(view => { const active = view.id === button.dataset.view; view.classList.toggle('on', active); view.hidden = !active; }); }));
document.querySelectorAll('[data-range]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-range]').forEach(item => item.classList.remove('on')); button.classList.add('on'); renderTrend(Number(button.dataset.range)); }));
document.querySelectorAll('[data-postab]').forEach(button => button.addEventListener('click', () => renderPOS(button.dataset.postab)));
if (SUPABASE_READY) requireSupabase().auth.getSession().then(({ data: sessionData }) => { if (sessionData.session) loadBusinessData(); });
